### ISSUE TITLE
How do I change the defaults? lagging the login loading spinkit

### ISSUE THREAD

**Issue by zuwuko** [leocavalcante/password-dart#3]
Seems like defaults are lagging the login loading spinkit animation. How do I turn down the settings on this password hashing?
Spinkit i'm using: https://github.com/jogboms/flutter_spinkit/

**Comment by leocavalcante** [comment]
You can try to decrease the [iteration count on the algorithm constructor ](https://github.com/leocavalcante/password-dart/blob/master/lib/src/algorithms/pbkdf2.dart#L26), but actually you shouldn't be using this package in Flutter, password hashing and verification is meant for server-side.
