### ISSUE TITLE
UI freezes while hashing

### ISSUE THREAD

**Issue by fathah** [leocavalcante/password-dart#4]
When I hash the password, my app UI is freezing. Is there any way?

**Comment by leocavalcante** [comment]
You actually shouldn't be hashing passwords in the client-side, this is a server task.
And if you really need to do heavy computations like cryptography, you should move it outside the main/UI thread, then your app can still at least show a spinner/progress bar.
Another tip is to decrease the iteration count, headsup that this makes the hashing less secure.
